# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dipl_face_detection_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 741)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fon = QtWidgets.QLabel(self.centralwidget)
        self.fon.setGeometry(QtCore.QRect(0, 0, 1151, 741))
        self.fon.setAcceptDrops(True)
        self.fon.setText("")
        self.fon.setPixmap(QtGui.QPixmap("../../фон/dfbd.jpeg"))
        self.fon.setScaledContents(True)
        self.fon.setObjectName("fon")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setEnabled(False)
        self.camera.setGeometry(QtCore.QRect(500, 80, 541, 511))
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.camera_on = QtWidgets.QPushButton(self.centralwidget)
        self.camera_on.setGeometry(QtCore.QRect(640, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.camera_on.setFont(font)
        self.camera_on.setStyleSheet("background-color: rgb(0, 255, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.camera_on.setObjectName("camera_on")
        self.camera_off = QtWidgets.QPushButton(self.centralwidget)
        self.camera_off.setGeometry(QtCore.QRect(912, 620, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camera_off.setFont(font)
        self.camera_off.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.camera_off.setObjectName("camera_off")
        self.pickl_file = QtWidgets.QPushButton(self.centralwidget)
        self.pickl_file.setGeometry(QtCore.QRect(10, 700, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pickl_file.setFont(font)
        self.pickl_file.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0, 190);")
        self.pickl_file.setObjectName("pickl_file")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(15, 61, 451, 321))
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255,200);")
        self.listWidget.setDragEnabled(False)
        self.listWidget.setObjectName("listWidget")
        self.load_file = QtWidgets.QPushButton(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(130, 700, 131, 28))
        self.load_file.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0 ,0 , 0, 200);\n"
"font: 14pt \"Old English Text MT\";")
        self.load_file.setObjectName("load_file")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(20, 400, 441, 281))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.pushButton_label = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_label.setGeometry(QtCore.QRect(280, 700, 121, 31))
        self.pushButton_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0 ,0 , 0, 200);\n"
"font: 14pt \"Old English Text MT\";")
        self.pushButton_label.setObjectName("pushButton_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_on.setText(_translate("MainWindow", "COMPARE"))
        self.camera_off.setText(_translate("MainWindow", "Close_cam"))
        self.pickl_file.setText(_translate("MainWindow", "Pickl_file"))
        self.load_file.setText(_translate("MainWindow", "Load_File"))
        self.pushButton_label.setText(_translate("MainWindow", "Load_image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
