# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dipl_face_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#python -m PyQt5.uic.pyuic -x dipl_face_detection.ui -o dipl_face_detection.py

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 741)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fon = QtWidgets.QLabel(self.centralwidget)
        self.fon.setGeometry(QtCore.QRect(0, 0, 1151, 741))
        self.fon.setAcceptDrops(True)
        self.fon.setText("")
        self.fon.setPixmap(QtGui.QPixmap("../../фон/dfbd.jpeg"))
        self.fon.setScaledContents(True)
        self.fon.setObjectName("fon")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setEnabled(False)
        self.camera.setGeometry(QtCore.QRect(500, 80, 541, 511))
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.camera_on = QtWidgets.QPushButton(self.centralwidget)
        self.camera_on.setGeometry(QtCore.QRect(640, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.camera_on.setFont(font)
        self.camera_on.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.camera_on.setObjectName("camera_on")
        self.camera_off = QtWidgets.QPushButton(self.centralwidget)
        self.camera_off.setGeometry(QtCore.QRect(912, 620, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camera_off.setFont(font)
        self.camera_off.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.camera_off.setObjectName("camera_off")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 311, 291))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255, 25);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 370, 351, 161))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255,80);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pickl_file = QtWidgets.QPushButton(self.centralwidget)
        self.pickl_file.setGeometry(QtCore.QRect(20, 560, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pickl_file.setFont(font)
        self.pickl_file.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255, 0);")
        self.pickl_file.setObjectName("pickl_file")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_on.setText(_translate("MainWindow", "COMPARE"))
        self.camera_off.setText(_translate("MainWindow", "Close_cam"))
        self.pickl_file.setText(_translate("MainWindow", "Pickl_file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
